# Data Preprocessing

## Setup Notebook

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
import sys
from pathlib import Path
import pandas as pd

from wtfd.data.preprocessing import WindFarmProcessor

## Setup Paths

In [3]:
project_root = Path(os.getcwd()).parent
RAW_DATA_ROOT = project_root / "data" / "raw" / "zenodo_windfarm_data"
PROCESSED_DATA_DIR = project_root / "data" / "processed"
CONFIG_PATH = project_root / "config" / "feature_map.yaml"

# Ensure the processed directory exists
PROCESSED_DATA_DIR.mkdir(parents=True, exist_ok=True)

## Process Windfarm Data

In [4]:
# Initialize
processor = WindFarmProcessor(config_path=CONFIG_PATH, window_days=3)

In [5]:
# 1. Process Raw -> Parquet (Only run this once or when data changes)
processor.process_all_turbines(RAW_DATA_ROOT, PROCESSED_DATA_DIR)

Processing Farm A:

Farm A: 100%|██████████████████████████████████████████████████████████████████████| 22/22 [00:13<00:00,  1.62turbine/s]

Processing Farm B:

Farm B: 100%|██████████████████████████████████████████████████████████████████████| 15/15 [00:23<00:00,  1.57s/turbine]

Processing Farm C:

Farm C: 100%|██████████████████████████████████████████████████████████████████████| 58/58 [04:03<00:00,  4.20s/turbine]

## Load Processed Data

In [6]:
# 2. Load Parquet -> Memory (Run this whenever starting a modeling session)
df = processor.load_processed_dataset(PROCESSED_DATA_DIR)

Combining 95 turbines into master dataset...
Dropping 10 constant indicators: ['has_amb_temp', 'has_wind_speed', 'has_pitch_angle', 'has_active_power', 'has_gen_speed', 'has_gearbox_oil_temp', 'has_transformer_temp', 'has_nacelle_temp', 'has_hub_temp', 'has_vibration_raw']
Success. Final dataset shape: (5242948, 23)

In [7]:
df.info()
display(df.head())
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5242948 entries, 0 to 5242947
Data columns (total 23 columns):
 #   Column                Dtype
---  ------                -----
 0   time_stamp            datetime64[ns]
 1   asset_id              int64
 2   farm_id               object
 3   amb_temp              float64
 4   wind_speed            float64
 5   pitch_angle           float64
 6   active_power          float64
 7   gen_speed             float64
 8   gearbox_oil_temp      float64
 9   transformer_temp      float64
 10  nacelle_temp          float64
 11  hub_temp              float64
 12  yaw_error             float64
 13  has_yaw_error         int64
 14  vibration_raw         float64
 15  hydraulic_temp        float64
 16  has_hydraulic_temp    int64
 17  temp_delta_gearbox    float64
 18  temp_delta_hydraulic  float64
 19  power_efficiency      float64
 20  temp_trend_24h        float64
 21  rpm_volatility        float64
 22  target                int64
dtypes: datetime64[ns](1), float64(17), int64(4), object(1)
memory usage: 920.0+ MB

,time_stamp,asset_id,farm_id,amb_temp,wind_speed,pitch_angle,active_power,gen_speed,gearbox_oil_temp,transformer_temp,...,has_yaw_error,vibration_raw,hydraulic_temp,has_hydraulic_temp,temp_delta_gearbox,temp_delta_hydraulic,power_efficiency,temp_trend_24h,rpm_volatility,target
0,2022-01-01 00:00:00,0,A,18.0,4.1,-0.3,37.662,1254.9,45.0,73.666667,...,1,13.8,32.0,1,27.0,14.0,0.546452,NaN,NaN,0
1,2022-01-01 00:10:00,0,A,18.0,4.1,-0.3,31.730,1251.9,45.0,73.666667,...,1,7.1,32.0,1,27.0,14.0,0.460382,NaN,NaN,0
2,2022-01-01 00:20:00,0,A,18.0,4.1,-0.3,34.488,1251.1,45.0,73.666667,...,1,9.5,32.0,1,27.0,14.0,0.500399,NaN,NaN,0
3,2022-01-01 00:30:00,0,A,18.0,4.4,-0.5,44.568,1259.9,45.0,73.666667,...,1,25.4,32.0,1,27.0,14.0,0.523197,NaN,NaN,0
4,2022-01-01 00:40:00,0,A,18.0,5.5,-1.5,99.174,1288.2,46.0,73.666667,...,1,32.8,32.0,1,28.0,14.0,0.596087,NaN,NaN,0

,time_stamp,asset_id,amb_temp,wind_speed,pitch_angle,active_power,gen_speed,gearbox_oil_temp,transformer_temp,nacelle_temp,...,has_yaw_error,vibration_raw,hydraulic_temp,has_hydraulic_temp,temp_delta_gearbox,temp_delta_hydraulic,power_efficiency,temp_trend_24h,rpm_volatility,target
count,5242948,5.242948e+06,5.242948e+06,5.242948e+06,5.242948e+06,5.242948e+06,5.242948e+06,5.242948e+06,5.242948e+06,5.242948e+06,...,5.242948e+06,5.242948e+06,5.242948e+06,5.242948e+06,5.242660e+06,4.383595e+06,5.236118e+06,5.228980e+06,5.239623e+06,5.242948e+06
mean,2023-01-16 03:05:20.091330816,2.487676e+01,2.365264e+01,6.827278e+00,4.495359e+00,4.273028e+01,1.009439e+03,5.073164e+01,4.661249e+01,2.027241e+01,...,8.361485e-01,1.617368e+01,2.657636e+01,8.361485e-01,2.707901e+01,7.736005e-01,1.473930e-01,1.834301e-02,1.683464e+02,9.080769e-04
min,2022-01-01 00:00:00,0.000000e+00,-2.732000e+02,-1.490000e+01,-2.990000e+00,-1.073400e+01,-3.999900e+02,-2.110500e+03,0.000000e+00,-1.168300e+02,...,0.000000e+00,-1.858250e-01,0.000000e+00,0.000000e+00,-2.817350e+03,-8.308000e+02,-7.246571e+03,-2.144269e+03,0.000000e+00,0.000000e+00
25%,2022-10-05 03:50:00,1.100000e+01,1.800000e+01,4.191000e+00,-1.800000e+00,3.290200e-02,6.980044e+02,4.600000e+01,3.535000e+01,8.715000e+00,...,1.000000e+00,1.742750e-01,2.009000e+01,1.000000e+00,1.880050e+01,-7.760000e+00,7.534264e-05,-3.137500e+00,4.578035e+01,0.000000e+00
50%,2023-01-15 22:20:00,2.100000e+01,2.500000e+01,6.680000e+00,-1.400000e+00,3.120400e-01,1.155210e+03,5.143650e+01,4.045450e+01,1.639600e+01,...,1.000000e+00,2.820250e-01,2.657636e+01,1.000000e+00,2.488900e+01,-4.300000e+00,6.287700e-04,-3.600000e-02,1.159875e+02,0.000000e+00
75%,2023-05-08 06:50:00,4.200000e+01,2.915400e+01,9.890000e+00,9.064000e-01,7.896585e-01,1.509839e+03,5.500000e+01,5.616667e+01,3.000000e+01,...,1.000000e+00,4.193333e+00,2.952900e+01,1.000000e+00,3.200000e+01,1.100000e+01,9.205175e-04,3.000000e+00,2.546583e+02,0.000000e+00
max,2024-02-06 16:30:00,5.600000e+01,1.044300e+03,6.000000e+01,9.387000e+01,7.425120e+02,1.786578e+03,4.586480e+02,1.180000e+02,7.000000e+01,...,1.000000e+00,8.232000e+02,1.511800e+03,1.000000e+00,4.312045e+02,1.488055e+03,3.813079e+05,2.136078e+03,8.942382e+02,1.000000e+00
std,NaN,1.778590e+01,7.932802e+00,5.920968e+00,1.598866e+01,1.336220e+02,5.801099e+02,2.229829e+01,1.777114e+01,1.327817e+01,...,3.701408e-01,5.991696e+01,8.975731e+00,3.701408e-01,2.337038e+01,1.215492e+01,1.716315e+02,9.690776e+00,1.635074e+02,3.012063e-02

## Sandbox